### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ucbrise/cirrus#1]
I would like to point out that identifiers like “[`_INPUT_H_`](https://github.com/ucbrise/cirrus/blob/4a084d35e7353022dcbc05e2341f67d52d792f57/src/InputReader.h#L1 "Update candidate")” and “[`_MFMODEL_H_`](https://github.com/ucbrise/cirrus/blob/e24f60500cd3d31b722b863a425305542a17b536/src/MFModel.h#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jcarreira** [comment]
Fixed.

**Comment by elfring** [comment]
Thanks for your adjustment of affected include guards.
