### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [ucbrise/cirrus#2]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “CircularBuffer”](https://github.com/ucbrise/cirrus/blob/c4df6eb4b5f44d99199aa77dcfcba5c8eeda3574/src/CircularBuffer.h#L22 "Destructor for CircularBuffer").

**Comment by jcarreira** [comment]
Fixed.
