### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [ucbrise/cirrus#3]
Would you like to [wrap any pointer variables](https://github.com/ucbrise/cirrus/blob/a7743a8fa7856da9d608cb346fb8df6d9fbc1237/src/PSSparseServerInterface.cpp#L77 "Update candidate: PSSparseServerInterface::get_lr_sparse_model_inplace()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by elfring** [comment]
I would appreciate a more constructive feedback for this issue.

**Comment by jcarreira** [comment]
Would you like to create a PR to fix this issue? I don't have many cycles to look into this right now.

**Comment by elfring** [comment]
Can it be acceptable to put affected character buffers on the stack (instead of using dynamic memory allocation)?
