### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [ucbrise/cirrus#9]
I find that include guards like “[`MODEL_H_`](https://github.com/ucbrise/cirrus/blob/6b7c303fce3f59ec26f927e0c6cd8305ede50768/src/Model.h#L1)” and “[`TASKS_H_`](https://github.com/ucbrise/cirrus/blob/6b7c303fce3f59ec26f927e0c6cd8305ede50768/src/Tasks.h#L1)” are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by jcarreira** [comment]
Please create a PR and I will be happy to merge it in.
